# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.post_voter:
        public: false
        class: AppBundle\Security\PostVoter
        arguments: ['@request_stack']
        tags:
            - { name: security.voter }

    app.security.access_denied_handler:
        class: AppBundle\Security\AccessDeniedHandler
        arguments: ['@router', '@session']

    app.validator.e164_number:
        class: AppBundle\Validator\Constraints\E164NumberValidator
        arguments: ['@twilio.client']
        tags:
            - { name: validator.constraint_validator }

    app.listener.twilio_request:
        class: AppBundle\EventSubscriber\TwilioRequestListener
        arguments: ['@twilio.request_validator']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    twilio.client:
        class: Twilio\Rest\Client
        arguments: ['%twilio_sid%', '%twilio_token%']

    twilio.request_validator:
        class: Twilio\Security\RequestValidator
        arguments: ['%twilio_token%']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
