# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.post_voter:
        public: false
        class: AppBundle\Security\PostVoter
        arguments: ['@request_stack']
        tags:
            - { name: security.voter }

    app.security.access_denied_handler:
        class: AppBundle\Security\AccessDeniedHandler
        arguments: ['@router', '@session']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
